### ISSUE TITLE
Non domain classes

### ISSUE THREAD

**Issue by TonyVeigel** [rahulsom/swaggydoc#10]
Does this work with response objects that are not domain classes? If not, is there any plan to make it work with say plain groovy objects? 

Thanks!

**Comment by TonyVeigel** [comment]
I did implement this, and it does seem to work for plain groovy objects. However, when I introduce a list to the class as outlined below, then I get a null pointer exception. 
```groovy
@ApiModel
class Example{
       int test
       List<something> somethings
}
```

**Comment by rahulsom** [comment]
@TonyVeigel I'm not sure if I've covered your use case in the commit c2bcc19. Would you mind trying out the latest code on your project?
Also if it doesn't work, can you add to the test case?

`@ApiModel` is not supported so far. So all the fancy stuff with inheritance is not likely to work.

**Comment by TonyVeigel** [comment]
Works perfect! Thank you very much, especially for the fast response. Will you be releasing this fix?

**Comment by rahulsom** [comment]
I'll release it today. Thanks!
