### ISSUE TITLE
Dynamic documentation of resources in UrlMappings

### ISSUE THREAD

**Issue by gefilte** [rahulsom/swaggydoc#11]
I've started working on this problem in my fork. My changes are pretty significant though, so I'm not sure if they're where you want to go with this. Feel free to check out my fork:
https://github.com/gefilte/swaggydoc

My main goal is to make the documentation generation more DRY: eliminate documentation annotations that repeat what is already specified in code.

It's still a work in process, but the changes I've made currently work like so:
* existing functionality is all still supported (your specs all still pass)
* controllers used as resources in UrlMappings will be automatically documented (meaning, all their operations) given solely the @Api annotation on the controller
* hierarchical path relationships established in UrlMappings are properly documented, with the necessary parameters added to all operations
* annotations (swaggy or low-level) for UrlMapped controllers will augment/override the dynamically set values

I plan to add some additional dynamic features as well (e.g., discovery of response types.)

**Comment by rahulsom** [comment]
@gefilte Looks good so far.

**Comment by gefilte** [comment]
Can you cut a release with my changes?

**Comment by rahulsom** [comment]
`0.10` released. Thanks.
