### ISSUE TITLE
responseContainer attribute ignored

### ISSUE THREAD

**Issue by VenkataKotra** [rahulsom/swaggydoc#12]
When generating response schema @ApiOperation is ignoring responseContainer attribute
e.g. - @ApiOperation(value = 'List demos', response = Demo, responseContainer = 'list') should display JSON array of Demo object in the schema, but it is displaying just the Demo object (no array).

**Comment by rahulsom** [comment]
I'll see if I can get to it. If you can throw in a unit test in the mean time, that would speed things up.
