### ISSUE TITLE
SwaggyDataService#getModels goes into an infinite loop

### ISSUE THREAD

**Issue by felipecao** [rahulsom/swaggydoc#24]
When I tried to use Swaggydoc annotations in my company's source code, SwaggyDataService#getModels would go into an infinite loop. The problem is that the Queue allows repetition, so, for instance, whenever a pair of domain classes referenced each other, both would go into the Queue for indefinite times. Also, for knownTypes, this method does a lot of processing to discard it at the end of the method.

I wanted to create a pull request, but it's tied to another pull request, which is waiting to be merged: https://github.com/rahulsom/swaggydoc/pull/21. In the meanwhile, the following suggested changes fix these problems:

static final List knownTypes = [int, Integer, long, Long, float, Float, double, Double, String, **boolean, Boolean**]

...

                    while (m.size()) {
                      Class model = m.poll()

                      ** if(model && model in knownTypes){
                        break
                    } **
...
                    if (f instanceof GrailsDomainClassProperty) {
                            def genericType = domainClass?.associationMap?.getAt(f.name)
                            if (genericType **&& !m.contains(genericType)**) {
                                m.add(genericType)
                            } else {
                                log.warn "No type args found for ${f.name}"
                            }
                        } else {
                            **if(!m.contains(f.genericType.actualTypeArguments[0])){**
                                m.add(f.genericType.actualTypeArguments[0])
                            }
                        }
                    } else {
                        **if(!m.contains(f.type)){**
                            m.add(f.type)
                        }
                    }

**Comment by rahulsom** [comment]
I could not reproduce the infinite loop. Are you using version 0.15, which is the latest?
