### ISSUE TITLE
Endless loop when domain class reference itself

### ISSUE THREAD

**Issue by prokhor-ozornin** [rahulsom/swaggydoc#26]
When a domain class have a mapped property that references itself (and the same table in database, for example, a tree of categories) and a controller /api/show/someController request is received, this library goes into an endless loop with a high CPU load. Graphical swaggydoc interface also doesn't work in that scenario. This is a stopper BUG.

**Comment by rahulsom** [comment]
What version are you using? Also do you have an example domain class you can provide?
A unit test to demonstrate this would be most appreciated.

**Comment by prokhor-ozornin** [comment]
Hi ! Thanks for the attention.

I am using version 0.17 (latest), but previous versions also seem to have this problem.

I was able to reproduce it with the following domain class and a RESTful controller. 
Controller really doesn't matter, the problem is in 'static hasMany' line, when a domain class references itself (graphs and trees of objects). If you comment out this line, calling /api will show swaggy UI, and clicking on "category" link will list all api methods as usual. If you leave it as it is, calling /api will show swaggy UI and force a high CPU load as if in a loop, and clicking "category" link will do nothing, as well as calling /api/show/category.

Grails version 2.5.

-- Domain --

package swaggy

import com.wordnik.swagger.annotations.ApiModel
import com.wordnik.swagger.annotations.ApiModelProperty

@ApiModel(value = 'Category')
class Category
{
  @ApiModelProperty(value = 'Name of category', required = true)
  String name

  //@ApiModelProperty(value = 'Parent categories', required = false)
  //Set<Category> parents = []

  static hasMany = [parents : Category]

  static constraints =
  {
    name nullable : false, blank : false
  }

  static mapping =
  {
    table 'categories'
    id generator : 'identity'
    sort 'name'
    cache true
    autoImport false

    /*parents(
      joinTable : [name : 'categories_hierarchy', key : 'node_id', column : 'parent_id']
    )*/
  }
}

-- Controller --
package swaggy

import com.wordnik.swagger.annotations.Api
import com.wordnik.swagger.annotations.ApiOperation
import grails.converters.JSON
import grails.rest.RestfulController

@Api(value = 'Categories')
class CategoryController extends RestfulController<Category>
{
  CategoryController()
  {
    super(Category)
  }

  @ApiOperation(value = 'List all categories', httpMethod = 'GET')
  def all()
  {
    render Category.list() as JSON
  }
}
---

**Comment by rahulsom** [comment]
Thanks for the test case. I've added it to the tests and have fixed the problem. It will be part of 0.18.

**Comment by prokhor-ozornin** [comment]
Nice ! Seems to be working ...
