### ISSUE TITLE
Some problems with Swaggydoc Plugin grails 3.2.1

### ISSUE THREAD

**Issue by smalints** [rahulsom/swaggydoc#58]
I added the SwaggyDoc-plugin to the dependencies in my build.gradle script by adding: 
`compile "org.grails.plugins:swaggydoc-grails3:0.28.0"`

And configure it by `https://rahulsom.github.io/swaggydoc/`.
In IntelliJ I see the Swaggydoc-dependency added to my list of libraries.

After starting my Grails-application via the grails run-app command and opening my application by entering `http://localhost:8080/api/`. And find some errors in console log(see in image) and in intellij console.

![console log](https://cloud.githubusercontent.com/assets/19852104/20886357/210ad88a-bb0f-11e6-8b71-2b4f0b28da46.png). 

![intellijj console](https://cloud.githubusercontent.com/assets/19852104/20886434/6d5113d0-bb0f-11e6-8338-cab7ea1d5eff.png)

**Comment by jaikishore08** [comment]
When we create grails application inside intellij we will get the following dependency inside application.yaml file.
runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.11.6"
We need to replace this with the following :
runtime "org.grails.plugins:asset-pipeline"

This error will be resolved.

**Comment by smalints** [comment]
@jaikishore08 Thanks!
