### ISSUE TITLE
Code breaks when the domain class has explicit type defined for hasMany attribute

### ISSUE THREAD

**Issue by vjunloc** [rahulsom/swaggydoc#6]
I have a domain class Demo

package org.example

class Demo {
	String title
	String description
	
	List features
	
	static hasMany =[features: Feature]
    static constraints = {
    }
}

When i use @ApiOperation(response = Demo) , 
The code throws an exception java.util.List doesn't have actualTypeArguments property

Basically code breaks at getTypeDescriptor() function, when it tries to evaluate "field.genericType.actualTypeArguments" 

Let me know, if you need a complete example.

**Comment by rahulsom** [comment]
This seems to work.

```groovy
List<Feature> features
```

When you have an implicit collection, grails creates a Set with generic type specified.
When you provide an explicit collection, you **must** provide the generic type.

**Comment by vjunloc** [comment]
Agreed, but it is a common practice to not specify the generic type( in fact the official docs also have this ), because grails automatically infers the type based on hasMany clause.

**Comment by rahulsom** [comment]
I've got it in a snapshot. It'll take me a while to write some unit tests. I'll do a release after that, unless you're in production.

**Comment by vjunloc** [comment]
No, we're not in production yet

**Comment by rahulsom** [comment]
Fixed in 0.7

**Comment by vjunloc** [comment]
That was quick, thanks
