### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by VenkataKotra** [rahulsom/swaggydoc#9]
Do you have any documentation on how to use this plugin? I've added the following configuration to config.groovy
```
swaggydoc {
    contact = "rahul.som@gmail.com"
    description = """\
        | This is a sample server Petstore server.  You can find out more about Swagger
        | at <a href="http://swagger.wordnik.com">http://swagger.wordnik.com</a> or on irc.freenode.net, #swagger.
        | For this sample,
        | you can use the api key "special-key" to test the authorization filters""".stripMargin()
    license = "Apache 2.0"
    licenseUrl = "http://www.apache.org/licenses/LICENSE-2.0.html"
    termsOfServiceUrl = "http://helloreverb.com/terms/"
    title = "Swaggydoc Demo App"
    apiVersion = "1.0"
}
```
I've also added  compile ":swaggydoc:0.8" to BuildConfig.groovy. Do we need to run any command to generate dcoumentation?

**Comment by rahulsom** [comment]
Please look at https://github.com/rahulsom/swaggydoc#usage. It shows how you mark your controllers for generating documentation.
Once you do that, when your app is running, you can browse to `/api` (assuming you haven't customized UrlMappings) and see the generated swagger documentation.

**Comment by VenkataKotra** [comment]
Thanks. It worked!! Do you know how to handle customized UrlMappings?

**Comment by rahulsom** [comment]
The plugin does not use direct urls. It always uses the grails link generator, so the url to point your browser would change when you have custom mappings, but the plugin would still work.

**Comment by VenkataKotra** [comment]
Makes sense. Thank you!!!
